// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPUwJTjhnjT9j-B3D9hTWSFbWrzlSKAxU',
    appId: '1:53921266677:web:8094bfe0f1510181297ebc',
    messagingSenderId: '53921266677',
    projectId: 'omar-mustafa',
    authDomain: 'omar-mustafa.firebaseapp.com',
    storageBucket: 'omar-mustafa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA0q9YZ8Dv8FLpzy71rgTBe5ZHaGeE2iM',
    appId: '1:53921266677:android:98e5b06b4b27b9ac297ebc',
    messagingSenderId: '53921266677',
    projectId: 'omar-mustafa',
    storageBucket: 'omar-mustafa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoqjD70RTXO-QB58w2emL3uDTyqXT52mM',
    appId: '1:53921266677:ios:16c5f22cf752c9d7297ebc',
    messagingSenderId: '53921266677',
    projectId: 'omar-mustafa',
    storageBucket: 'omar-mustafa.appspot.com',
    androidClientId:
        '53921266677-tu36p9msemkvc3cub6rd3itjp4o624kq.apps.googleusercontent.com',
    iosClientId:
        '53921266677-bblir7l1v37dadc2m7pkhqv2dcr8qb9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.omarMostafa',
  );
}
